In [1]:
import numpy as np

In [2]:
np.pi #Pi value

3.141592653589793

In [3]:
np.inf #Inifinity

inf

In [4]:
a = np.array([1,2,3]) #One dimentional arry

In [5]:
a

array([1, 2, 3])

In [6]:
type(a)

numpy.ndarray

In [7]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]]) #Multi dimentional array

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
b.size #Size of Array

9

In [10]:
b[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b.shape #Array matrix (row, cols)

(3, 3)

In [12]:
b[0] #1st row

array([1, 2, 3])

In [13]:
b[2] #2nd row

array([7, 8, 9])

In [14]:
b[-1] #last row

array([7, 8, 9])

In [15]:
b[::-1] #Reverse matrix

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [16]:
b[0][2] #1st row 3rd item

3

In [17]:
b[1][1] #2nd row 2nd item

5

In [18]:
b[:,:2] #: - all rows | :2 - 1st 2 cols

array([[1, 2],
       [4, 5],
       [7, 8]])

In [19]:
b[:,:1] #: - all rows | :1 - 1st col

array([[1],
       [4],
       [7]])

In [20]:
b[:,:-1] #: - all rows | :-1 - all cols but not last

array([[1, 2],
       [4, 5],
       [7, 8]])

In [21]:
b[:,:] #: - all rows | : all cols

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
b[:,:-2] #: - all rows | :-2 all but not last 2 cols

array([[1],
       [4],
       [7]])

In [23]:
b[:,:-3] #: - all rows | :-2 all but not last 3 cols

array([], shape=(3, 0), dtype=int32)

In [24]:
b[1,:] #1 - 1st rows | : - all cols

array([4, 5, 6])

In [25]:
b[1,:1] #1 - 1st rows | :1 - 1st col

array([4])

In [26]:
b[1,:2] #1 - 1st rows | :2 - 1st and 2nd col

array([4, 5])

In [27]:
b[1:,:2] #1: - All rows from 1st | :2 - 1st and 2nd col

array([[4, 5],
       [7, 8]])

In [28]:
b.min() #Min element

1

In [29]:
b.max() #Max element

9

In [30]:
b.sum() #Sum of all elements in array

45

In [31]:
b.sum(axis=1) # sum of all rows

array([ 6, 15, 24])

In [32]:
b.sum(axis=0) #sum of all cols

array([12, 15, 18])

In [33]:
c = np.array([[1,1,1],[2,2,2],[3,3,3]])

In [34]:
c

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [35]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
np.dot(b,c) # Dot array product

array([[14, 14, 14],
       [32, 32, 32],
       [50, 50, 50]])

In [37]:
np.dot(c,b)

array([[12, 15, 18],
       [24, 30, 36],
       [36, 45, 54]])

In [38]:
np.cross(b,c) #Cross Product

array([[-1,  2, -1],
       [-2,  4, -2],
       [-3,  6, -3]])

In [40]:
l = [1,3.2,3.3]
max(l)

3.3

In [41]:
z = {1: 2, 2: 1}

In [44]:
max_score = max(z.values())

In [45]:
1

1

In [46]:
max(z.items(), key = operator.itemgetter(1))[0]

NameError: name 'operator' is not defined