# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint
## Not for grades

## Learning Objective

The objective of this experiment is to understand Linear classifier.

## Dataset

#### History

This is a multivariate dataset introduced by R.A.Fisher (Father of Modern Statistics) for showcasing linear discriminant analysis. This is arguably the best known dataset in Feature Selection literature.


The data set contains 3 classes of 50 instances each, where each class refers to a type of iris plant. One class is linearly separable from the other 2; the latter are NOT linearly separable from each other. 

#### Description
The Iris dataset consists of 150 data instances. There are 3 classes (Iris Versicolor, Iris Setosa and Iris Virginica) each have 50 instances. 


For each flower we have the below data attributes 

- sepal length in cm
- sepal width in cm
- petal length in cm
- petal width in cm

To make our experiment easy we rename the classes  with numbers : 

    "0": setosa
    "1": versicolor
    "2": virginica
    

### Challenges

When we use the data with large number of features or dimensionality, models usually choke because

    1. Training time increases exponentially with number of features.
    2. Models have increasing risk of overfitting with increasing number of features.
    
To avoid the above mentioned problems while learning about data analysis, we use simple, well behaved, data that reduces the cognitive load, and makes it easier to debug as we are able to better comprehend the data we are working with.  

Hence, this is a good dataset to work on.

## Domain Information



Iris Plants are flowering plants with showy flowers. They are very popular among movie directors as it gives excellent background. 

They are predominantly found in dry, semi-desert, or colder rocky mountainous areas in Europe and Asia. They have long, erect flowering stems and can produce white, yellow, orange, pink, purple, lavender, blue or brown colored flowers. There are 260 to 300 types of iris.

![alt text](https://cdn-images-1.medium.com/max/1275/1*7bnLKsChXq94QjtAiRn40w.png)

As you could see, flowers have 3 sepals and 3 petals.  The sepals are usually spreading or drop downwards and the petals stand upright, partly behind the sepal bases. However, the length and width of the sepals and petals vary for each type.


### Setup Steps

In [0]:
!ls

07_LC_Iris_data.ipynb	    Data_setosa_virginica.csv	   sample_data
Data_setosa_versicolor.csv  Data_versicolor_virginica.csv


#### Importing Required Packages

In [0]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn import linear_model
import pandas as pd

#### Loading the data

There are three files choose one among those

* Data_setosa_versicolor.csv
* Data_setosa_virginica.csv
* Data_versicolor_virginica.csv

In [0]:
dataset = "Data_versicolor_virginica.csv"

In [0]:
data = pd.read_csv(dataset)

In [0]:
data.shape

(100, 5)

### Splitting the data into train and test sets 

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(data.values[:,:4], data.values[:,4], test_size=0.33, random_state=42)

In [0]:
# Let us see the size of train and  test sets
X_train.shape, X_test.shape

((67, 4), (33, 4))

In [0]:
# Let us see first five rows of the training data
X_train[:5]

array([[6. , 2.9, 4.5, 1.5],
       [6.8, 3.2, 5.9, 2.3],
       [5.7, 2.8, 4.5, 1.3],
       [6.5, 3. , 5.5, 1.8],
       [6.4, 3.2, 5.3, 2.3]])

In [0]:
y_train

array([1., 2., 1., 2., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1., 2., 1.,
       1., 1., 1., 1., 1., 2., 1., 2., 1., 2., 2., 2., 2., 1., 2., 2., 1.,
       2., 2., 2., 2., 1., 2., 1., 2., 2., 2., 1., 2., 2., 2., 2., 1., 1.,
       1., 2., 1., 1., 1., 2., 2., 2., 2., 2., 1., 2., 2., 1., 2., 2.])

### Training a  Linear Classifier 

In [0]:
linear_classifier = linear_model.SGDClassifier()

In [0]:
# Training or fitting the model with the train data
linear_classifier.fit(X_train,y_train)

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [0]:
# Testing the trained model
linear_classifier.predict(X_test)

array([2., 2., 2., 1., 1., 1., 2., 2., 1., 1., 1., 1., 2., 2., 2., 1., 2.,
       2., 1., 1., 2., 2., 1., 1., 2., 1., 1., 2., 1., 2., 1., 1., 2.])

In [0]:
# Calculating the score
linear_classifier.score(X_test,y_test)

0.9393939393939394